apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app: deploy-1
  name: example-pod2
spec:
  containers:
    - image: nginx
      name: example-container
      ports:
        - port: 80
          target_port : 8080