apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app: deploy-1
  name: example-pod2
spec:
  containers:
    - image: docker.io/library/nginx:latest
      name: example-container
      imagePullPolicy: IfNotPresent
