apiVersion: v1
kind: Job
metadata:
  name: matrix-mul
spec:
  containers:
    - name: gpu-container
      image: 192.168.1.12:5000/gpu-server:v1
      imagePullPolicy: IfNotPresent
      command:
        - "./job.py"
      env:
        - name: source-path
          value: /matrix-mul
        - name: job-name
          value: matrix-mul
        - name: partition
          value: dgx2
        - name: "N"
          value: "1"
        - name: ntasks-per-node
          value: "1"
        - name: cpus-per-task
          value: "6"
        - name: gres
          value: gpu:1
      volumeMounts:
        - name: share-data
          containerPath: "/matrix-mul"
  volumes:
    - name: share-data
      nfs:
        server: 192.168.1.12
        share: "/mnt/ShareFolder"