stages:
  - build
  - test
  - finish

build:
  stage: build
  script:
    - go mod tidy
    - echo "Compiling the code..."
    - bash ./script/clean.sh
    - bash ./script/build.sh CI
    - bash ./script/start.sh CI
    - echo "Compile and run complete."

test-static-analysis:
  stage: test
  script:
    - echo "Running go vet..."
    - go vet ./...

test-apiserver:
  stage: test
  script:
    - echo "Running unit tests for apiserver..."
    - go test minik8s/test/apiserver -cover -count=1

test-kubelet:
  stage: test
  script:
    - echo "Running unit tests for kubelet..."
    - go test minik8s/test/kubelet -cover -count=1

test-kubectl:
  stage: test
  script:
    - echo "Running unit tests for kubectl..."
    - go test minik8s/test/kubectl -cover -count=1

test-kubeproxy:
  stage: test
  script:
    - echo "Running unit tests for kubeproxy..."
    - go test minik8s/test/kubeproxy -cover -count=1

test-dns:
  stage: test
  script:
    - echo "Running unit tests for dns..."
    - go test minik8s/test/dns -cover -count=1

test-volume:
  stage: test
  script:
    - echo "Running unit tests for volume..."
    - go test minik8s/test/volume -cover -count=1

finish:
  stage: finish
  script:
    - ./script/stop.sh CI
    - echo "Finish testing"