stages:
  - build
  - test
  - finish

build:
  stage: build
  script:
    - go mod tidy
    - echo "Compiling the code..."
    - mkdir build && cd build && cmake .. && make -j`nproc` && cd ..
    - ./bin/apiserver > ./log/apiserver.log 2>&1 &
    - echo "start apiserver"
    - sleep 3
    - ./bin/kubelet > ./log/kubelet.log 2>&1 &
    - echo "start kubelet"
    - echo "Compile and run complete."

test-static-analysis:
  stage: test
  script:
    - echo "Running go vet..."
    - go vet ./...

test-apiserver:
  stage: test
  script:
    - echo "Running unit tests for apiserver..."
    - go test minik8s/test/apiserver -cover

test-kubelet:
  stage: test
  script:
    - echo "Running unit tests for kubelet..."
    - go test minik8s/test/kubelet -cover

test-kubectl:
  stage: test
  script:
    - echo "Running unit tests for kubectl..."
    - go test minik8s/test/kubectl -cover

test-kubeproxy:
  stage: test
  script:
    - echo "Running unit tests for kubeproxy..."
    - go test minik8s/test/kubeproxy -cover

test-dns:
  stage: test
  script:
    - echo "Running unit tests for kubeproxy..."
    - go test minik8s/test/dns -cover


finish:
  stage: finish
  script:
    - pkill apiserver
    - pkill kubelet
    - echo "Finish testing"