apiVersion: v1
kind: Pod
metadata:
  name: pod-on-docker-registry
  namespace: default
spec:
  containers:
    - name: test-container
      image: docker.io/shadownearby/ip_return:v1
      imagePullPolicy: IfNotPresent
