apiVersion: v1
kind: Pod
metadata:
  name: pod-on-master
  namespace: default
spec:
  selector:
    matchLabels:
      host: k8s-1
  containers:
    - name: test-container
      image: docker.io/shadownearby/ubuntu:latest
      imagePullPolicy: IfNotPresent
