apiVersion: v1
kind: Pod
metadata:
  name: pod-on-registry
  namespace: default
spec:
  selector:
    matchLabels:
      host: k8s-2
  containers:
    - name: test-container
      image: 192.168.1.12:5000/ip_return:v1
      imagePullPolicy: IfNotPresent
