apiVersion: v1
kind: Pod
metadata:
  name: pod-load
  namespace: default
  labels:
    app: deploy-1
spec:
  containers:
    - name: pod-load
      image: docker.io/shadownearby/system_load:v1
      imagePullPolicy: IfNotPresent
      resources:
        limit:
          memory: 500000000
      ports:
        - containerPort: 7070
          name: p2
    - name: pod-ip-return
      image: docker.io/shadownearby/ip_return:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: p1
  restartPolicy: Never
