apiVersion: v1
kind: Pod
metadata:
  name: pod-on-worker
  namespace: default
spec:
  selector:
    matchLabels:
     host: k8s-2
  containers:
  - name: test-container
    image: docker.io/shadownearby/ubuntu:latest
    imagePullPolicy: IfNotPresent