apiVersion: v1
kind: Replicas
metadata:
  name: ip-return-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: ip-return
      labels:
        app: nginx
    spec:
      containers:
        - name: ip-return-test
          image: docker.io/shadownearby/ip_return:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: p1
      restartPolicy: OnFailure
