apiVersion: v1
kind: Service
metadata:
  name: rs-fail-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: fail-deploy
  type: ClusterIP
  ports:
  - name: rs-ip-port
    protocol: TCP
    port: 20080
    targetPort: p1
  - name: rs-load-port
    protocol: TCP
    port: 27070
    targetPort: p2