apiVersion: v1
kind: Replicas
metadata:
  name: fail-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: pod-fail
      namespace: default
      labels:
        app: fail-deploy
    spec:
      containers:
      - name: pod-load
        image: docker.io/shadownearby/system_load:v1
        imagePullPolicy: IfNotPresent
        resources: 
          limit:
            memory: 200000000
        ports:
        - containerPort: 7070
          name: p2
