apiVersion: v1
kind: Service
metadata:
  name: rs-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  type: ClusterIP
  ports:
    - name: rs-service-port
      protocol: TCP
      port: 20922
      targetPort: p1
