apiVersion: v1
kind: Pod
metadata:
  name: monitor-pod
  namespace: default
  labels:
    app: deploy-1
    minik8s/prometheus-port: '14567'
spec:
  containers:
    - name: monitor-container
      image: docker.io/shadownearby/promethues_example_py:latest
      imagePullPolicy: IfNotPresent
