apiVersion: v1
kind: Replica
metadata:
  name: hpa-replicaset
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: hpa-test
      namespace: default
      labels:
        app: hpa-test
    spec:
      containers:
      - name: nginx_test
        image: docker.io/shadownearby/system_load:v1
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure