apiVersion: v1
kind: Service
metadata:
  name: hpa-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: hpa-test
  type: ClusterIP
  ports:
  - name: hpa-service-port
    protocol: TCP
    port: 20096
    targetPort: p1
  