apiVersion: v1
kind: workflow
name: app-yolo
startAt: preprocess
comment: using pipline to classify photo
states:
  preprocess:
    type: TaskState
    inputPath: "$.path"
    resultPath: "$.full_path"
    next: "judgePath"
  judgePath:
    type: ChoiceState
    choices:
      - variable: "$.full_path"
        StringEquals: ""
        next: errorState
    default: infer
  infer:
    type: TaskState
    inputPath: "$.full_path"
    resultPath: $.result"
    end: true
  errorState:
    type: FailState
    error: DefaultStateError
    cause: "file does not exist"
