apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  namespace: default
  labels:
    app: deploy-1
spec:
  selector:
    matchLabels:
     host: k8s-1
  containers:
  - name: example-container
    image: docker.io/hashicorp/http-echo:latest
    imagePullPolicy: IfNotPresent
    cmd:
    - "/http-echo"
    - "-listen=:8080"
    - "-text=hello"
    ports:
    - containerPort: 8080
      name: p1