apiVersion: v1
kind: Service
metadata:
  name: service-practice
  namespace: default
spec:
  selector:
    app: deploy-1
  type: ClusterIP
  ports:
  - name: service-port1
    protocol: TCP
    port: 30000
    targetPort: p1
  clusterIP: 10.10.0.2
  