apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy-1
  type: NodePort
  ports:
  - name: service-port1
    protocol: TCP
    nodePort: 29998
    targetPort: p1 