apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy-1
  type: ClusterIP
  ports:
    - name: service-port2
      protocol: TCP
      port: 29999
      targetPort: p1
