apiVersion: v1
kind: Volume
metadata:
  name: test-pv
spec:
  capacity:
    request:
      storage: 1000000
  accessMode: ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    server: 192.168.1.12
    share: "/mnt/ShareFolder"