apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy-1
  type: ClusterIP
  ports:
  - name: service-port1
    protocol: TCP
    port: 27888
    targetPort: p1
  