apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: default
spec:
  selector:
    matchLabels:
      app: deploy-2
  type: ClusterIP
  ports:
    - name: service-port2
      protocol: TCP
      port: 27889
      targetPort: p1
